robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers -----------------------------------------
  wheel_1_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_1_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  wheel_2_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_2_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  wheel_3_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_3_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  wheel_4_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_4_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}
